### ISSUE TITLE
Performance & storage footprint question

### ISSUE THREAD

**Issue by dj-nuo** [cgzirim/seek-tune#15]
Hi! Work looks amazing!
I have a few questions:

1. What's the storage footprint of 1 min audio? (e.g. it creates 1000 records in the database which results in 50 kb of storage use)
2. Do you have any performance observations? (e.g. 1 CPU core @ 3 GHz takes 30 sec to process & record to database, and 10 sec to retrieve from database). I understand it's very "depends on", but still :-)

**Comment by cgzirim** [comment]
@dj-nuo Thank you for the kind words.

### Storage Footprint:
From my analysis of a playlist of [1-minute songs](https://open.spotify.com/playlist/1sEwfb55rieGnKnEVlVXQL?si=18d13ea9f6ca4707), the number of fingerprints generated per song varies. The minimum number of fingerprints generated was 413, while the maximum was 4634. On average, each 1-minute song produces about 2466 fingerprint entries.

Each [fingerprint](https://github.com/cgzirim/seek-tune/blob/def9665408d97335aba3b10699a308973cc2b30e/shazam/fingerprint.go#L17) consists of a key (address) of 4 bytes and a value ([models.Couple](https://github.com/cgzirim/seek-tune/blob/def9665408d97335aba3b10699a308973cc2b30e/models/models.go#L3)) of 8 bytes, totaling 12 bytes per fingerprint. So, for a 1-minute song with an average of 2466 fingerprints, the storage requirement is approximately 29.592 kilobytes (12 * 2466). For a database containing 1000 such songs, the total storage footprint would be around 28.88 MB.

### Performance Observations:
Performance can vary, but here are some insights based on my setup:

- **CPU**: 12th Gen Intel(R) Core(TM) i7-1255U processor
- **Database Size**: 193 songs

For this setup I observed the following performance metrics:
- The processing time for the songs in the 1-minute songs playlist ranged from 289.13 milliseconds to 1274.95 milliseconds, with an average of 743.07 milliseconds.
- Searching for a match with a 4.24-minute song that generated 10,976 fingerprints took approximately 4.64 seconds.
- Searching for a match with a 20-second recording that generated 1,868 fingerprints took around 684 milliseconds.

These results suggest that the search time is generally proportional to the number of fingerprints generated and the database size. However, other factors such as hardware specifications can also influence performance.
